mixed-port: 7890
find-process-mode: strict
mode: rule
geodata-mode: true
geox-url:
  geoip: "https://ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.dat"
  geosite: "https://ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  mmdb: "https://ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country.mmdb"
log-level: debug
ipv6: true
external-controller: 127.0.0.1:9090
tcp-concurrent: true
global-client-fingerprint: chrome
unified-delay: true
#
dns:
  enable: true
  listen: 127.0.0.1:1053
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
#    - tls://1.12.12.12:853
#    - tls://223.5.5.5:853
#    - 9.9.9.9
#    - 1.1.1.1
#    - 8.8.8.8
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  nameserver:
#    - 223.5.5.5
#    - 119.29.29.29
#    - tls://dns.alidns.com
#    - tls://dot.pub
    - https://223.5.5.5/dns-query
    - https://223.6.6.6/dns-query
    - https://1.12.12.12/dns-query
    - https://120.53.53.53/dns-query
#    - https://dns.alidns.com/dns-query
#    - https://doh.pub/dns-query
#  fallback:
#    - 9.9.9.9
#    - 1.1.1.1
#    - 8.8.8.8
#    - tls://dns.quad9.net
#    - tls://1dot1dot1dot1.cloudflare-dns.com
#    - tls://dns.google
#     - https://9.9.9.9/dns-query
#     - https://1.1.1.1/dns-query
#     - https://8.8.8.8/dns-query
#    - https://dns.quad9.net/dns-query
#    - https://dns.cloudflare.com/dns-query
#    - https://dns.google/dns-query
#  fallback-filter:
#    geoip: true
#    geoip-code: CN
#    geosite:
#      - gfw
#    ipcidr:
#      - 240.0.0.0/4
#    domain:
#      - '+.google.com'
#      - '+.facebook.com'
#      - '+.youtube.com'
#
proxies:
  - name: cloudcone
    type: hysteria
    server: janeuorg.eu.org
    ports: 47000-48000
    auth_str: mzTPJ1l6Bx28697jXPpGmnsg1Dg2U3U9BxIlGNCum3qz5wot0C
    alpn:
      - h3
    protocol: udp
    up: 22
    down: 110
    sni: janeuorg.eu.org
    skip-cert-verify: false
    recv_window_conn: 11534336
    recv_window: 46137344
    disable_mtu_discovery: true
    fast-open: true
  - name: racknerd
    type: hysteria
    server: mareuorg.eu.org
    ports: 47000-48000
    auth_str: qbRDOWXRrcqXE5T8BGvuYSCBFvkdFbbYoRQF9twENeF15jwBKw
    alpn:
      - h3
    protocol: udp
    up: 22
    down: 110
    sni: mareuorg.eu.org
    skip-cert-verify: false
    recv_window_conn: 11534336
    recv_window: 46137344
    disable_mtu_discovery: true
    fast-open: true
  - name: virmach
    type: hysteria
    server: febeuorg.eu.org
    ports: 47000-48000
    auth_str: 2K7wmX8xMc1a1jiYHCHlJ6QnUjLbK8TF1nGKCqsG2rK8PuHqaj
    alpn:
      - h3
    protocol: udp
    up: 22
    down: 110
    sni: febeuorg.eu.org
    skip-cert-verify: false
    recv_window_conn: 11534336
    recv_window: 46137344
    disable_mtu_discovery: true
    fast-open: true
#
proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - auto
      - cloudcone
      - virmach
      - racknerd
  - name: auto
    type: url-test
    proxies:
      - cloudcone
      - virmach
      - racknerd
    url: 'https://www.gstatic.com/generate_204'
    interval: 300
#
rule-providers:
  mydirect:
    type: http
    behavior: domain
    path: ./ruleset/mydirect.yaml
    url: "https://ghproxy.com/https://raw.githubusercontent.com/bylheart/myrules/main/mydirect.txt"
    interval: 86400
  myproxy:
    type: http
    behavior: domain
    path: ./ruleset/myproxy.yaml
    url: "https://ghproxy.com/https://raw.githubusercontent.com/bylheart/myrules/main/myproxy.txt"
    interval: 86400
#
rules:
  - RULE-SET,mydirect,DIRECT
  - RULE-SET,myproxy,cloudcone
#  - GEOSITE,category-ads-all,REJECT
# 白名单模式
# GEOSITE规则
  - GEOSITE,google,PROXY
  - GEOSITE,apple-cn,DIRECT
  - GEOSITE,google-cn,DIRECT
  - GEOSITE,tld-cn,DIRECT
  - GEOSITE,category-games@cn,DIRECT
  - GEOSITE,private,DIRECT
  - GEOSITE,cn,DIRECT
  - GEOSITE,geolocation-!cn,PROXY
# GEOIP规则
  - GEOIP,google,PROXY
  - GEOIP,private,DIRECT
  - GEOIP,cn,DIRECT
  - MATCH,PROXY
# 黑名单模式
# GEOSITE规则
#  - GEOSITE,google,PROXY
#  - GEOSITE,geolocation-!cn,PROXY
#  - GEOSITE,gfw,PROXY
# GEOIP规则
#  - GEOIP,google,PROXY
#  - GEOIP,telegram,PROXY
#  - GEOIP,us,PROXY
#  - GEOIP,jp,PROXY
#  - MATCH,DIRECT
