mixed-port: 7890
allow-lan: true
bind-address: '*'
find-process-mode: strict
mode: rule
geox-url:
  geoip: "https://ghproxy.com/https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat"
  geosite: "https://ghproxy.com/https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat"
  mmdb: "https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/geoip/release/Country.mmdb"
log-level: info
ipv6: true
external-controller: 0.0.0.0:9090
global-client-fingerprint: chrome
profile:
  store-selected: true
#  store-fake-ip: true
geodata-mode: true
tcp-concurrent: true
#unified-delay: true
#
dns:
  enable: true
  prefer-h3: true
  listen: 0.0.0.0:1053
  ipv6: true
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
    - 9.9.9.9
    - 1.1.1.1
    - 8.8.8.8
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  fake-ip-filter:
    - dns.msftncsi.com
    - www.msftncsi.com
    - www.msftconnecttest.com
  nameserver:
#    - 223.5.5.5
#    - 119.29.29.29
#    - tls://dns.alidns.com
#    - tls://dot.pub
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.cloudflare.com/dns-query
    - https://dns.google/dns-query
#    - 'tls://8.8.4.4#dns'
#    - 'tls://1.0.0.1#dns'
#    - https://bdafc461.d.adguard-dns.com/dns-query
#    - tls://bdafc461.d.adguard-dns.com
#    - quic://bdafc461.d.adguard-dns.com
#    - https://dns.nextdns.io/8657cb
#  fallback:
#    - 9.9.9.9
#    - 1.1.1.1
#    - 8.8.8.8
#    - tls://dns.quad9.net
#    - tls://1dot1dot1dot1.cloudflare-dns.com
#    - tls://dns.google
#    - https://dns.quad9.net/dns-query
#    - https://dns.cloudflare.com/dns-query
#    - https://dns.google/dns-query
#  fallback-filter:
#    geoip: true
#    geoip-code: CN
#    geosite:
#      - gfw
#    ipcidr:
#      - 240.0.0.0/4
#    domain:
#      - '+.google.com'
#      - '+.facebook.com'
#      - '+.youtube.com'
#  proxy-server-nameserver:
#  - https://dns.alidns.com/dns-query
#  - https://doh.pub/dns-query
#  nameserver-policy:
#    "geosite:cn,private":
#    - https://doh.pub/dns-query
#    - https://dns.alidns.com/dns-query
#
proxies:
  - name: cloudcone
    type: hysteria
    server: janeuorg.eu.org
    ports: 47000-48000
    auth_str: aAhzlIo658FIihAekwVtPOmdQZQIUgr3pyyyuqvnT32k3dUHph
    alpn:
      - h3
    protocol: udp
    up: 11
    down: 55
    sni: janeuorg.eu.org
    skip-cert-verify: false
    recv_window_conn: 5767168
    recv_window: 23068672
    disable_mtu_discovery: true
    fast-open: true
  - name: racknerd
    type: hysteria
    server: mareuorg.eu.org
    ports: 47000-48000
    auth_str: gM19mB6fcmWZ3HgdnrDc10UldgyKkQApsML3NvljJfvy0cBWFF
    alpn:
      - h3
    protocol: udp
    up: 11
    down: 55
    sni: mareuorg.eu.org
    skip-cert-verify: false
    recv_window_conn: 5767168
    recv_window: 23068672
    disable_mtu_discovery: true
    fast-open: true
  - name: virmach
    type: hysteria
    server: febeuorg.eu.org
    ports: 47000-48000
    auth_str: 28ai7NcusJLHRcTjLnrNubljYrbGzwVzzMUJIO0uq5VDdD1clN
    alpn:
      - h3
    protocol: udp
    up: 11
    down: 55
    sni: febeuorg.eu.org
    skip-cert-verify: false
    recv_window_conn: 5767168
    recv_window: 23068672
    disable_mtu_discovery: true
    fast-open: true
#
proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - auto
      - cloudcone
      - virmach
      - racknerd
  - name: auto
    type: url-test
    proxies:
      - cloudcone
      - virmach
      - racknerd
    tolerance: 150
    url: 'https://www.gstatic.com/generate_204'
    interval: 300
#
rule-providers:
  antiad:
    type: http
    behavior: domain
    path: ./ruleset/antiad.yaml
    url: "https://ghproxy.com/https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-clash.yaml"
    interval: 86400
  mydirect:
    type: http
    behavior: domain
    path: ./ruleset/mydirect.yaml
    url: "https://ghproxy.com/https://raw.githubusercontent.com/bylheart/myrules/main/mydirect.txt"
    interval: 86400
  myproxy:
    type: http
    behavior: domain
    path: ./ruleset/myproxy.yaml
    url: "https://ghproxy.com/https://raw.githubusercontent.com/bylheart/myrules/main/myproxy.txt"
    interval: 86400
#
rules:
#  - RULE-SET,antiad,REJECT
  - RULE-SET,mydirect,DIRECT
  - RULE-SET,myproxy,cloudcone
#  - GEOSITE,category-ads-all,REJECT
# 白名单模式
# GEOSITE规则
  - GEOSITE,google,PROXY
  - GEOSITE,apple-cn,DIRECT
  - GEOSITE,google-cn,DIRECT
  - GEOSITE,tld-cn,DIRECT
  - GEOSITE,category-games@cn,DIRECT
  - GEOSITE,private,DIRECT
  - GEOSITE,cn,DIRECT
#  - GEOSITE,geolocation-!cn,PROXY
# GEOIP规则
#  - GEOIP,google,PROXY
  - GEOIP,private,DIRECT
  - GEOIP,cn,DIRECT
  - MATCH,PROXY
# 黑名单模式
# GEOSITE规则
#  - GEOSITE,google,PROXY
#  - GEOSITE,gfw,PROXY
#  - GEOSITE,geolocation-!cn,PROXY
# GEOIP规则
#  - GEOIP,google,PROXY
#  - GEOIP,telegram,PROXY
#  - GEOIP,us,PROXY
#  - GEOIP,jp,PROXY
#  - MATCH,DIRECT
