mixed-port: 10801
allow-lan: true
bind-address: "*"
find-process-mode: strict
global-client-fingerprint: chrome
ipv6: true
mode: rule
log-level: debug
external-controller: 0.0.0.0:9093
external-controller-tls: 0.0.0.0:9443
geox-url:
  geoip: "https://ghproxy.com/https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat"
  geosite: "https://ghproxy.com/https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat"
  mmdb: "https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/geoip/release/Country.mmdb"
tls:
  certificate: string
  private-key: string
  custom-certifactes:
    - |
      -----BEGIN CERTIFICATE-----
      format/pem...
      -----END CERTIFICATE-----
experimental:
profile:
  store-selected: false
  store-fake-ip: true
#
dns:
  enable: true
  prefer-h3: true
  listen: 0.0.0.0:1053
  ipv6: true
  default-nameserver:
    - 114.114.114.114
    - 8.8.8.8
    - tls://1.12.12.12:853
    - tls://223.5.5.5:853
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - localhost.ptlogin2.qq.com
    - dns.msftncsi.com
    - www.msftncsi.com
    - www.msftconnecttest.com
  nameserver-policy:
    'www.baidu.com': '114.114.114.114'
    '+.internal.crop.com': '10.0.0.1'
    'geosite:cn': https://doh.pub/dns-query
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  fallback:
    - tls://8.8.4.4
    - tls://1.1.1.1
  proxy-server-nameserver:
    - https://doh.pub/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    geosite:
      - gfw
    ipcidr:
      - 240.0.0.0/4
    domain:
      - '+.google.com'
      - '+.facebook.com'
      - '+.youtube.com'
#
hosts:
  '*.clash.dev': 127.0.0.1
  'alpha.clash.dev': '::1'
  test.com: [1.1.1.1, 2.2.2.2]
  baidu.com: google.com
  clash.lan: clash
#
proxies:
  - name: cloudcone
    type: hysteria
    server: www.janeuorg.eu.org
    ports: 47000-48000
    auth_str: C9WnqjZQRpdVh9npSSgecRYt6vIj2QJ0JZunupvkXIcPk1VNcs
    alpn:
      - h3
    protocol: udp
    up: 11
    down: 55
    sni: www.janeuorg.eu.org
    skip-cert-verify: false
    recv_window_conn: 5767168
    recv_window: 23068672
    disable_mtu_discovery: true
    fast-open: true
  - name: racknerd
    type: hysteria
    server: www.mareuorg.eu.org
    ports: 47000-48000
    auth_str: t4Y3iSvXo3Zi9XA2Q0fkMpINy0fWb27riXtQD0d7sFc0vLNaRp
    alpn:
      - h3
    protocol: udp
    up: 11
    down: 55
    sni: www.mareuorg.eu.org
    skip-cert-verify: false
    recv_window_conn: 5767168
    recv_window: 23068672
    disable_mtu_discovery: true
    fast-open: true
  - name: virmach
    type: hysteria
    server: www.febeuorg.eu.org
    ports: 47000-48000
    auth_str: D4ZdDKDGDR6982oLCI74102WoCu3NvpWbQXTHzw4wId02uJPut
    alpn:
      - h3
    protocol: udp
    up: 11
    down: 55
    sni: www.febeuorg.eu.org
    skip-cert-verify: false
    recv_window_conn: 5767168
    recv_window: 23068672
    disable_mtu_discovery: true
    fast-open: true
#
proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - auto
      - cloudcone
      - virmach
      - racknerd
  - name: auto
    type: url-test
    proxies:
      - cloudcone
      - virmach
      - racknerd
    url: 'https://www.gstatic.com/generate_204'
    interval: 300
#
rule-providers:
  mydirect:
    behavior: domain
    interval: 259200
    path: /ruleset/mydirect.yaml
    type: http
    url: "https://ghproxy.com/https://raw.githubusercontent.com/bylheart/myrules/main/mydirect.txt"
  myproxy:
    behavior: domain
    interval: 259200
    path: /ruleset/myproxy.yaml
    type: http
    url: "https://ghproxy.com/https://raw.githubusercontent.com/bylheart/myrules/main/myproxy.txt"
  antiad:
    behavior: domain
    interval: 259200
    path: /ruleset/antiad.yaml
    type: http
    url: "https://ghproxy.com/https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-clash.yaml"
#
rules:
  - RULE-SET,mydirect,DIRECT
  - RULE-SET,myproxy,PROXY
#  - RULE-SET,antiad,REJECT
#  - GEOSITE,category-ads-all,REJECT
# 白名单模式
# GEOSITE规则
  - GEOSITE,google,PROXY
  - GEOSITE,private,DIRECT
  - GEOSITE,apple-cn,DIRECT
  - GEOSITE,google-cn,DIRECT
  - GEOSITE,tld-cn,DIRECT
  - GEOSITE,category-games@cn,DIRECT
  - GEOSITE,geolocation-!cn,PROXY
  - GEOSITE,cn,DIRECT
# GEOIP规则
  - GEOIP,google,PROXY
  - GEOIP,private,DIRECT
  - GEOIP,cn,DIRECT
  - MATCH,PROXY
# 黑名单模式
# GEOSITE规则
#  - GEOSITE,google,PROXY
#  - GEOSITE,gfw,PROXY
#  - GEOSITE,greatfire,PROXY
# GEOIP规则
#  - GEOIP,google,PROXY
#  - GEOIP,telegram,PROXY
#  - GEOIP,us,PROXY
#  - GEOIP,jp,PROXY
#  - MATCH,DIRECT
