port: 7890
socks-port: 7891
geodata-mode: true
tcp-concurrent: true
allow-lan: false
mode: rule
log-level: info
ipv6: true
external-controller: 127.0.0.1:9090
#
sniffer:
  enable: true
  sniffing:
    - tls
    - http
  skip-domain:
    - 'Mijia Cloud'
    - 'dlg.io.mi.com'
    - '+.apple.com'
  # - '*.baidu.com'
  force-domain:
  # - '+'
    - 'google.com'
  #port-whitelist:
  # - 80
  # - 443
  # - 8000-9000
hosts:
  # '*.clash.dev': 127.0.0.1
  # '.dev': 127.0.0.1
  # 'alpha.clash.dev': '::1'
#
dns:
  enable: true
  listen: 127.0.0.1:1053
  ipv6: false
  default-nameserver:
    - 223.5.5.5 
    - 119.29.29.29 
#    - 1.1.1.1
#    - 8.8.8.8
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.1/16
  # use-hosts: true
  fake-ip-filter:
  #   - '*.lan'
  #   - '*.linksys.com'
  #   - '+.pool.ntp.org'
  #   - localhost.ptlogin2.qq.com
    - dns.msftncsi.com
    - www.msftncsi.com
    - www.msftconnecttest.com
  nameserver:
    - tls://dns.alidns.com
    - tls://dot.pub
#    - https://dns.alidns.com/dns-query
#    - https://doh.pub/dns-query
#  fallback:
#    - tls://1dot1dot1dot1.cloudflare-dns.com
#    - tls://dns.google
#    - https://dns.alidns.com/dns-query
#    - https://doh.pub/dns-query
#    - https://dns.cloudflare.com/dns-query
#    - https://dns.google/dns-query
#  fallback-filter:
#    geoip: true
#    geoip-code: CN
#    geosite:
#      - gfw
#    ipcidr:
#      - 240.0.0.0/4
#    domain:
#      - '+.google.com'
#      - '+.facebook.com'
#      - '+.youtube.com'
#
proxies:  
  - name: "trojan"
    type: trojan
    server: shcu2.forgebukkit.com
    port: 51234
    password: a097adf8-79cd-4335-ad26-2755300059c9
    udp: true
    sni: mareuorg.eu.org
    alpn:
      - h2
      - http/1.1
  - name: "vless-ws-racknerd"
    type: vless
    server: my.aprfreenom.gq
    port: 443
    uuid: a097adf8-79cd-4335-ad26-2755300059c9
    udp: true
    tls: true
    network: ws
    servername: racknerd.mayfreenom.gq
    ws-opts:
      path: "/wstlsws"
      headers:
        Host: racknerd.mayfreenom.gq
  - name: "vless-ws-cloudcone"
    type: vless
    server: www.aprfreenom.gq
    port: 443
    uuid: 98dc5de8-d1dd-458e-9db0-08669c6614a7
    udp: true
    tls: true
    network: ws
    servername: cloudcone.mayfreenom.gq
    ws-opts:
      path: "/wstlsws"
      headers:
        Host: cloudcone.mayfreenom.gq
  - name: "vless-ws-virmach"
    type: vless
    server: virmach.marfreenom.gq
    port: 443
    uuid: 321a8837-94f0-4295-9dc0-0dacf630ed96
    udp: true
    tls: true
    network: ws
    servername: virmach.mayfreenom.gq
    ws-opts:
      path: "/wstlsws"
      headers:
        Host: virmach.mayfreenom.gq
  - name: "vless-ws-euserv"
    type: vless
    server: euserv.mayfreenom.gq
    port: 443
    uuid: a6e72c5d-8f5a-4bd5-b1ec-d6fb97d2443d
    udp: true
    tls: true
    network: ws
    servername: euserv.mayfreenom.gq
    ws-opts:
      path: "/wstlsws"
      headers:
        Host: euserv.mayfreenom.gq
#
proxy-groups:
  - name: "auto" 
    type: url-test
    proxies:
      - trojan
      - vless-ws-racknerd
      - vless-ws-cloudcone
      - vless-ws-virmach
      - vless-ws-euserv
    tolerance: 100
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
  - name: "fallback-auto"
    type: fallback
    proxies:
      - trojan
      - vless-ws-racknerd
      - vless-ws-cloudcone
      - vless-ws-virmach
      - vless-ws-euserv
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
  - name: "load-balance"
    type: load-balance
    proxies:
      - trojan
      - vless-ws-racknerd
      - vless-ws-cloudcone
      - vless-ws-virmach
      - vless-ws-euserv
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
  - name: PROXY
    type: select
    proxies:
      - auto
      - fallback-auto
      - load-balance
      - trojan
      - vless-ws-racknerd
      - vless-ws-cloudcone
      - vless-ws-virmach
      - vless-ws-euserv
#
rule-providers:      
  LocalAreaNetwork:
    type: http
    behavior: classical
    path: ./ruleset/LocalAreaNetwork.yaml
    url: "https://github.mayfreenom.gq/ACL4SSR/ACL4SSR/raw/master/Clash/Providers/LocalAreaNetwork.yaml"
    interval: 43200
  UnBan:
    type: http
    behavior: classical
    path: ./ruleset/UnBan.yaml
    url: "https://github.mayfreenom.gq/ACL4SSR/ACL4SSR/raw/master/Clash/Providers/UnBan.yaml"
    interval: 43200
  BanAD:
    type: http
    behavior: classical
    path: ./ruleset/BanAD.yaml
    url: "https://github.mayfreenom.gq/ACL4SSR/ACL4SSR/raw/master/Clash/Providers/BanAD.yaml"
    interval: 43200
  BanProgramAD:
    type: http
    behavior: classical
    path: ./ruleset/BanProgramAD.yaml
    url: "https://github.mayfreenom.gq/ACL4SSR/ACL4SSR/raw/master/Clash/Providers/BanProgramAD.yaml"
    interval: 43200
  BanEasyList:
    type: http
    behavior: classical
    path: ./ruleset/BanEasyList.yaml
    url: "https://github.mayfreenom.gq/ACL4SSR/ACL4SSR/raw/master/Clash/Providers/BanEasyList.yaml"
    interval: 43200
  BanEasyListChina:
    type: http
    behavior: classical
    path: ./ruleset/BanEasyListChina.yaml
    url: "https://github.mayfreenom.gq/ACL4SSR/ACL4SSR/raw/master/Clash/Providers/BanEasyListChina.yaml"
    interval: 43200
  BanEasyPrivacy:
    type: http
    behavior: classical
    path: ./ruleset/BanEasyPrivacy.yaml
    url: "https://github.mayfreenom.gq/ACL4SSR/ACL4SSR/raw/master/Clash/Providers/BanEasyPrivacy.yaml"
    interval: 43200
  GoogleFCM:
    type: http
    behavior: classical
    path: ./ruleset/GoogleFCM.yaml
    url: "https://github.mayfreenom.gq/ACL4SSR/ACL4SSR/raw/master/Clash/Providers/Ruleset/GoogleFCM.yaml"
    interval: 43200
  GoogleCN:
    type: http
    behavior: classical
    path: ./ruleset/GoogleCN.yaml
    url: "https://github.mayfreenom.gq/ACL4SSR/ACL4SSR/raw/master/Clash/Providers/Ruleset/GoogleCN.yaml"
    interval: 43200
  Google:
    type: http
    behavior: classical
    path: ./ruleset/Google.yaml
    url: "https://github.mayfreenom.gq/ACL4SSR/ACL4SSR/raw/master/Clash/Providers/Ruleset/Google.yaml"
    interval: 43200
  SteamCN:
    type: http
    behavior: classical
    path: ./ruleset/SteamCN.yaml
    url: "https://github.mayfreenom.gq/ACL4SSR/ACL4SSR/raw/master/Clash/Providers/Ruleset/SteamCN.yaml"
    interval: 43200
  OneDrive:
    type: http
    behavior: classical
    path: ./ruleset/OneDrive.yaml
    url: "https://github.mayfreenom.gq/ACL4SSR/ACL4SSR/raw/master/Clash/Providers/Ruleset/OneDrive.yaml"
    interval: 43200
  Microsoft:
    type: http
    behavior: classical
    path: ./ruleset/Microsoft.yaml
    url: "https://github.mayfreenom.gq/ACL4SSR/ACL4SSR/raw/master/Clash/Providers/Ruleset/Microsoft.yaml"
    interval: 43200
  Apple:
    type: http
    behavior: classical
    path: ./ruleset/AppleCN.yaml
    url: "https://github.mayfreenom.gq/ACL4SSR/ACL4SSR/raw/master/Clash/Providers/Ruleset/Apple.yaml"
    interval: 43200
  Telegram:
    type: http
    behavior: classical
    path: ./ruleset/Telegram.yaml
    url: "https://github.mayfreenom.gq/ACL4SSR/ACL4SSR/raw/master/Clash/Providers/Ruleset/Telegram.yaml"
    interval: 43200
  NetEaseMusic:
    type: http
    behavior: classical
    path: ./ruleset/NetEaseMusic.yaml
    url: "https://github.mayfreenom.gq/ACL4SSR/ACL4SSR/raw/master/Clash/Providers/Ruleset/NetEaseMusic.yaml"
    interval: 43200
  Epic:
    type: http
    behavior: classical
    path: ./ruleset/Epic.yaml
    url: "https://github.mayfreenom.gq/ACL4SSR/ACL4SSR/raw/master/Clash/Providers/Ruleset/Epic.yaml"
    interval: 43200
  Sony:
    type: http
    behavior: classical
    path: ./ruleset/Sony.yaml
    url: "https://github.mayfreenom.gq/ACL4SSR/ACL4SSR/raw/master/Clash/Providers/Ruleset/Sony.yaml"
    interval: 43200
  Steam:
    type: http
    behavior: classical
    path: ./ruleset/Steam.yaml
    url: "https://github.mayfreenom.gq/ACL4SSR/ACL4SSR/raw/master/Clash/Providers/Ruleset/Steam.yaml"
    interval: 43200
  YouTube:
    type: http
    behavior: classical
    path: ./ruleset/YouTube.yaml
    url: "https://github.mayfreenom.gq/ACL4SSR/ACL4SSR/raw/master/Clash/Providers/Ruleset/YouTube.yaml"
    interval: 43200
  Netflix:
    type: http
    behavior: classical
    path: ./ruleset/Netflix.yaml
    url: "https://github.mayfreenom.gq/ACL4SSR/ACL4SSR/raw/master/Clash/Providers/Ruleset/Netflix.yaml"
    interval: 43200
  AmazonIp:
    type: http
    behavior: ipcidr
    path: ./ruleset/AmazonIp.yaml
    url: "https://github.mayfreenom.gq/ACL4SSR/ACL4SSR/raw/master/Clash/Providers/Ruleset/AmazonIp.yaml"
    interval: 43200
  Bahamut:
    type: http
    behavior: classical
    path: ./ruleset/Bahamut.yaml
    url: "https://github.mayfreenom.gq/ACL4SSR/ACL4SSR/raw/master/Clash/Providers/Ruleset/Bahamut.yaml"
    interval: 43200
  BilibiliHMT:
    type: http
    behavior: classical
    path: ./ruleset/BilibiliHMT.yaml
    url: "https://github.mayfreenom.gq/ACL4SSR/ACL4SSR/raw/master/Clash/Providers/Ruleset/BilibiliHMT.yaml"
    interval: 43200
  Bilibili:
    type: http
    behavior: classical
    path: ./ruleset/Bilibili.yaml
    url: "https://github.mayfreenom.gq/ACL4SSR/ACL4SSR/raw/master/Clash/Providers/Ruleset/Bilibili.yaml"
    interval: 43200
  ChinaMedia:
    type: http
    behavior: classical
    path: ./ruleset/ChinaMedia.yaml
    url: "https://github.mayfreenom.gq/ACL4SSR/ACL4SSR/raw/master/Clash/Providers/ChinaMedia.yaml"
    interval: 43200
  ProxyMedia:
    type: http
    behavior: classical
    path: ./ruleset/ProxyMedia.yaml
    url: "https://github.mayfreenom.gq/ACL4SSR/ACL4SSR/raw/master/Clash/Providers/ProxyMedia.yaml"
    interval: 43200
  ProxyGFWlist:
    type: http
    behavior: classical
    path: ./ruleset/ProxyGFWlist.yaml
    url: "https://github.mayfreenom.gq/ACL4SSR/ACL4SSR/raw/master/Clash/Providers/ProxyGFWlist.yaml"
    interval: 43200
  ChinaIp:
    type: http
    behavior: ipcidr
    path: ./ruleset/ChinaIp.yaml
    url: "https://github.mayfreenom.gq/ACL4SSR/ACL4SSR/raw/master/Clash/Providers/ChinaIp.yaml"
    interval: 43200
  ChinaDomain:
    type: http
    behavior: classical
    path: ./ruleset/ChinaDomain.yaml
    url: "https://github.mayfreenom.gq/ACL4SSR/ACL4SSR/raw/master/Clash/Providers/ChinaDomain.yaml"
    interval: 43200
  ChinaCompanyIp:
    type: http
    behavior: ipcidr
    path: ./ruleset/ChinaCompanyIp.yaml
    url: "https://github.mayfreenom.gq/ACL4SSR/ACL4SSR/raw/master/Clash/Providers/ChinaCompanyIp.yaml"
    interval: 43200
  Download:
    type: http
    behavior: classical
    path: ./ruleset/Download.yaml
    url: "https://github.mayfreenom.gq/ACL4SSR/ACL4SSR/raw/master/Clash/Providers/Download.yaml"
    interval: 43200
  Wechat:
    type: http
    behavior: classical
    path: ./ruleset/Download.yaml
    url: "https://github.mayfreenom.gq/ACL4SSR/ACL4SSR/raw/master/Clash/Providers/Ruleset/Wechat.yaml"
    interval: 43200
  reject:
    type: http
    behavior: domain
    url: "https://github.mayfreenom.gq/Loyalsoldier/clash-rules/raw/release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 43200
  icloud:
    type: http
    behavior: domain
    url: "https://github.mayfreenom.gq/Loyalsoldier/clash-rules/raw/release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 43200
  apple:
    type: http
    behavior: domain
    url: "https://github.mayfreenom.gq/Loyalsoldier/clash-rules/raw/release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 43200
  googlelist:
    type: http
    behavior: domain
    url: "https://github.mayfreenom.gq/Loyalsoldier/clash-rules/raw/release/google.txt"
    path: ./ruleset/googlelist.yaml
    interval: 43200
  proxy:
    type: http
    behavior: domain
    url: "https://github.mayfreenom.gq/Loyalsoldier/clash-rules/raw/release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 43200
  direct:
    type: http
    behavior: domain
    url: "https://github.mayfreenom.gq/Loyalsoldier/clash-rules/raw/release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 43200
  private:
    type: http
    behavior: domain
    url: "https://github.mayfreenom.gq/Loyalsoldier/clash-rules/raw/release/private.txt"
    path: ./ruleset/private.yaml
    interval: 43200
  gfw:
    type: http
    behavior: domain
    url: "https://github.mayfreenom.gq/Loyalsoldier/clash-rules/raw/release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 43200
  greatfire:
    type: http
    behavior: domain
    url: "https://github.mayfreenom.gq/Loyalsoldier/clash-rules/raw/release/greatfire.txt"
    path: ./ruleset/greatfire.yaml
    interval: 43200
  tld-not-cn:
    type: http
    behavior: domain
    url: "https://github.mayfreenom.gq/Loyalsoldier/clash-rules/raw/release/tld-not-cn.txt"
    path: ./ruleset/tld-not-cn.yaml
    interval: 43200
  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://github.mayfreenom.gq/Loyalsoldier/clash-rules/raw/release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 43200
  cncidr:
    type: http
    behavior: ipcidr
    url: "https://github.mayfreenom.gq/Loyalsoldier/clash-rules/raw/release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 43200
  lancidr:
    type: http
    behavior: ipcidr
    url: "https://github.mayfreenom.gq/Loyalsoldier/clash-rules/raw/release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 43200
  applications:
    type: http
    behavior: classical
    url: "https://github.mayfreenom.gq/Loyalsoldier/clash-rules/raw/release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 43200
  anti-AD:
    type: http
    behavior: domain
    path: ./ruleset/anti-AD.yaml
    url: "https://github.mayfreenom.gq/privacy-protection-tools/anti-AD/raw/master/anti-ad-clash.yaml"
    interval: 43200
  anti-AD-white:
    type: http
    behavior: domain
    path: ./ruleset/anti-AD.yaml
    url: "https://github.mayfreenom.gq/privacy-protection-tools/dead-horse/raw/master/anti-ad-white-for-clash.yaml"
    interval: 43200
  mydirect:
    type: http
    behavior: domain
    path: ./ruleset/mydirect.yaml
    url: "https://github.mayfreenom.gq/bylheart/clashrule/raw/main/mydirect.txt"
    interval: 43200
  myproxy:
    type: http
    behavior: domain
    path: ./ruleset/myproxy.yaml
    url: "https://github.mayfreenom.gq/bylheart/clashrule/raw/main/myproxy.txt"
    interval: 43200
  myrules:
    type: http
    behavior: domain
    path: ./ruleset/myrules.yaml
    url: "https://github.mayfreenom.gq/bylheart/clashrule/raw/main/myrules.txt"
    interval: 43200
#
rules:
  - RULE-SET,mydirect,DIRECT
  - RULE-SET,myproxy,PROXY  
#  - RULE-SET,anti-AD,REJECT
#  - RULE-SET,anti-AD-white,DIRECT
  - RULE-SET,myrules,vless-ws-euserv
#  - RULE-SET,googlelist,PROXY
#  - RULE-SET,GoogleFCM,PROXY
#  - RULE-SET,GoogleCN,PROXY
# 拒绝
#  - GEOSITE,category-ads-all,REJECT
#  - RULE-SET,reject,REJECT  
#  - RULE-SET,BanAD,REJECT
#  - RULE-SET,BanProgramAD,REJECT
#  - RULE-SET,BanEasyList,REJECT
#  - RULE-SET,BanEasyListChina,REJECT
#  - RULE-SET,BanEasyPrivacy,REJECT
# 直连
#  - GEOSITE:tld-cn
#  - GEOSITE:category-games@cn
#  - GEOSITE:private
#  - GEOSITE:cn
  - RULE-SET,applications,DIRECT
  - RULE-SET,private,DIRECT
  - RULE-SET,icloud,DIRECT
  - RULE-SET,apple,DIRECT
  - RULE-SET,direct,DIRECT
  - RULE-SET,lancidr,DIRECT
  - RULE-SET,cncidr,DIRECT
  - RULE-SET,LocalAreaNetwork,DIRECT
  - RULE-SET,UnBan,DIRECT
  - RULE-SET,OneDrive,DIRECT
  - RULE-SET,Microsoft,DIRECT
  - RULE-SET,Apple,DIRECT
  - RULE-SET,NetEaseMusic,DIRECT
  - RULE-SET,Epic,DIRECT
  - RULE-SET,Sony,DIRECT
  - RULE-SET,SteamCN,DIRECT
  - RULE-SET,BilibiliHMT,DIRECT
  - RULE-SET,Bilibili,DIRECT  
  - RULE-SET,ChinaMedia,DIRECT
  - RULE-SET,ChinaIp,DIRECT
  - RULE-SET,ChinaDomain,DIRECT
  - RULE-SET,ChinaCompanyIp,DIRECT
  - RULE-SET,Download,DIRECT
  - RULE-SET,Wechat,DIRECT
# 代理
#  - GEOSITE,geolocation-!cn,PROXY
#  - RULE-SET,proxy,PROXY
#  - RULE-SET,tld-not-cn,PROXY
#  - RULE-SET,gfw,PROXY
#  - RULE-SET,greatfire,PROXY
#  - RULE-SET,telegramcidr,PROXY 
#  - RULE-SET,Google,PROXY
#  - RULE-SET,Telegram,PROXY
#  - RULE-SET,Steam,PROXY
#  - RULE-SET,YouTube,PROXY
#  - RULE-SET,Netflix,PROXY
#  - RULE-SET,AmazonIp,PROXY
#  - RULE-SET,Bahamut,PROXY
#  - RULE-SET,ProxyMedia,PROXY
#  - RULE-SET,ProxyGFWlist,PROXY
# 其他
#  - GEOIP,private,DIRECT
#  - GEOIP,cn,DIRECT
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,PROXY
