# port: 7890 # HTTP(S) 代理服务器端口
# socks-port: 7891 # SOCKS5 代理端口
mixed-port: 10801 # HTTP(S) 和 SOCKS 代理混合端口
# redir-port: 7892 # 透明代理端口，用于 Linux 和 MacOS

# Transparent proxy server port for Linux (TProxy TCP and TProxy UDP)
# tproxy-port: 7893

#  find-process-mode has 3 values:always, strict, off
#  - always, 开启，强制匹配所有进程
#  - strict, 默认，由 mihomo 判断是否开启
#  - off, 不匹配进程，推荐在路由器上使用此模式
find-process-mode: strict

mode: rule

#自定义 geodata url
geox-url:
  geoip: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.dat"
  geosite: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  mmdb: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.metadb"

geo-auto-update: true # 是否自动更新 geodata
geo-update-interval: 6 # 更新间隔，单位：小时

log-level: silent # 日志等级 silent/error/warning/info/debug

ipv6: true # 开启 IPv6 总开关，关闭阻断所有 IPv6 链接和屏蔽 DNS 请求 AAAA 记录

external-controller: 127.0.0.1:9090 # RESTful API 监听地址

unified-delay: true

tcp-concurrent: true # TCP 并发连接所有 IP, 将使用最快握手的 TCP

# 全局 TLS 指纹，优先低于 proxy 内的 client-fingerprint
# 可选： "chrome","firefox","safari","ios","random","none" options.
# Utls is currently support TLS transport in TCP/grpc/WS/HTTP for VLESS/Vmess and trojan.
global-client-fingerprint: chrome

#  TCP keep alive interval
keep-alive-interval: 15

profile: # 存储 select 选择记录
  store-selected: false

  # 持久化 fake-ip
  store-fake-ip: true

# DNS配置
dns:
  cache-algorithm: arc
  enable: true # 关闭将使用系统 DNS
  prefer-h3: true # 开启 DoH 支持 HTTP/3，将并发尝试
  listen: 127.0.0.1:1053 # 开启 DNS 服务器监听
  # ipv6: false # false 将返回 AAAA 的空结果
  # ipv6-timeout: 300 # 单位：ms，内部双栈并发时，向上游查询 AAAA 时，等待 AAAA 的时间，默认 100ms
  # 用于解析 nameserver，fallback 以及其他DNS服务器配置的，DNS 服务域名
  # 只能使用纯 IP 地址，可使用加密 DNS
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
    #- tls://223.5.5.5:853
    #- tls://223.6.6.6:853
    #- tls://1.12.12.12:853
    #- tls://120.53.53.53:853
    #- system # append DNS server from system configuration. If not found, it would print an error log and skip.
  enhanced-mode: fake-ip # or redir-host

  fake-ip-range: 198.18.0.1/16 # fake-ip 池设置

  # use-hosts: true # 查询 hosts

  # 配置不使用fake-ip的域名
  # fake-ip-filter:
  #   - '*.lan'
  #   - localhost.ptlogin2.qq.com

  # DNS主要域名配置
  # 支持 UDP，TCP，DoT，DoH，DoQ
  # 这部分为主要 DNS 配置，影响所有直连，确保使用对大陆解析精准的 DNS
  nameserver:
    - tls://223.5.5.5:853 # DNS over TLS
    - tls://223.6.6.6:853
    - tls://1.12.12.12:853
    - tls://120.53.53.53:853
    - https://223.5.5.5/dns-query
    - https://223.6.6.6/dns-query
    - https://1.12.12.12/dns-query
    - https://120.53.53.53/dns-query
    #- https://dns.alidns.com/dns-query
    #- https://doh.pub/dns-query # DNS over HTTPS
    #- 114.114.114.114 # default value
    #- 8.8.8.8 # default value
    #- https://dns.alidns.com/dns-query#h3=true # 强制 HTTP/3，与 perfer-h3 无关，强制开启 DoH 的 HTTP/3 支持，若不支持将无法使用
    #- https://mozilla.cloudflare-dns.com/dns-query#DNS&h3=true # 指定策略组和使用 HTTP/3
    #- dhcp://en0 # dns from dhcp
    #- quic://dns.adguard.com:784 # DNS over QUIC
    # - '8.8.8.8#en0' # 兼容指定DNS出口网卡

  # 当配置 fallback 时，会查询 nameserver 中返回的 IP 是否为 CN，非必要配置
  # 当不是 CN，则使用 fallback 中的 DNS 查询结果
  # 确保配置 fallback 时能够正常查询
  # fallback:
    #- https://dns.google/dns-query
    #- https://dns.cloudflare.com/dns-query
    #- https://dns.quad9.net/dns-query
    #- https://8.8.8.8/dns-query
    #- https://8.8.4.4/dns-query
    #- https://1.1.1.1/dns-query
    #- https://1.0.0.1/dns-query
    #- https://9.9.9.9/dns-query
    #- https://149.112.112.112/dns-query
  #   - tcp://1.1.1.1
  #   - 'tcp://1.1.1.1#ProxyGroupName' # 指定 DNS 过代理查询，ProxyGroupName 为策略组名或节点名，过代理配置优先于配置出口网卡，当找不到策略组或节点名则设置为出口网卡

  # 专用于节点域名解析的 DNS 服务器，非必要配置项
  # 配置服务器若查询失败将使用 nameserver，非并发查询
  # proxy-server-nameserver:
  # - https://dns.google/dns-query
  # - tls://one.one.one.one

  # 配置 fallback 使用条件
  # fallback-filter:
  #   geoip: true # 配置是否使用 geoip
  #   geoip-code: CN # 当 nameserver 域名的 IP 查询 geoip 库为 CN 时，不使用 fallback 中的 DNS 查询结果
  #   配置强制 fallback，优先于 IP 判断，具体分类自行查看 geosite 库
  #   geosite:
  #     - gfw
  #   如果不匹配 ipcidr 则使用 nameservers 中的结果
  #   ipcidr:
  #     - 240.0.0.0/4
  #   domain:
  #     - '+.google.com'
  #     - '+.facebook.com'
  #     - '+.youtube.com'

  # 配置查询域名使用的 DNS 服务器
  #nameserver-policy:
    #   'www.baidu.com': '114.114.114.114'
    #   '+.internal.crop.com': '10.0.0.1'
    #"geosite:cn,private,apple":
      #- https://doh.pub/dns-query
      #- https://dns.alidns.com/dns-query
    #"geosite:category-ads-all": rcode://success
    #"www.baidu.com,+.google.cn": [223.5.5.5, https://dns.alidns.com/dns-query]
    ## global，dns 为 rule-providers 中的名为 global 和 dns 规则订阅，
    ## 且 behavior 必须为 domain/classical，当为 classical 时仅会生效域名类规则
    # "rule-set:global,dns": 8.8.8.8
#
proxy-groups:
  - name: PROXY
    type: select
    use:
      - provider
    proxies:
      - FALLBACK
      - URL-TEST
  - name: "FALLBACK"
    type: fallback
    use:
      - provider
    url: "https://cp.cloudflare.com/generate_204"
    interval: 300
  - name: "URL-TEST"
    type: url-test
    use:
      - provider
    url: "https://cp.cloudflare.com/generate_204"
    interval: 300
  - name: OTHER
    type: select
    use:
      - provider
#
# Mihomo 格式的节点或支持 *ray 的分享格式
proxy-providers:
  provider:
    type: http # http 的 path 可空置,默认储存路径为 homedir的proxies文件夹,文件名为url的md5
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/bylheart/clash/master/config/2.yaml"
    interval: 3600
    path: ./provider/subscription.yaml # 默认只允许存储在 mihomo 的 Home Dir，如果想存储到任意位置，添加环境变量 SKIP_SAFE_PATH_CHECK=1
    health-check:
      enable: true
      interval: 600
      # lazy: true
      url: https://cp.cloudflare.com/generate_204
      # expected-status: 204 # 当健康检查返回状态码与期望值不符时，认为节点不可用
    override: # 覆写节点加载时的一些配置项
      skip-cert-verify: true
      udp: true
      # down: "50 Mbps"
      # up: "10 Mbps"
      # dialer-proxy: proxy
      # interface-name: tailscale0
      # routing-mark: 233
      # ip-version: ipv4-prefer
#
rule-providers:
  myrules:
    behavior: classical
    interval: 259200
    path: ./rule/myrules.yaml # 默认只允许存储在 mihomo 的 Home Dir，如果想存储到任意位置，添加环境变量 SKIP_SAFE_PATH_CHECK=1
    type: http # http 的 path 可空置,默认储存路径为 homedir的rules文件夹,文件名为url的md5
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/bylheart/myrules/main/myrules.txt"
  mydirect:
    behavior: domain
    interval: 259200
    path: ./rule/mydirect.yaml
    type: http
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/bylheart/myrules/main/mydirect.txt"
  myproxy:
    behavior: domain
    interval: 259200
    path: ./rule/myproxy.yaml
    type: http
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/bylheart/myrules/main/myproxy.txt"
  # Advertising:
    # behavior: classical
    # interval: 43200
    # path: ./rule/Advertising.yaml
    # type: http
    # url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Advertising/Advertising.yaml"
  # Advertising_Domain:
    # behavior: domain
    # interval: 43200
    # path: ./rule/Advertising_Domain.yaml
    # type: http
    # url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Advertising/Advertising_Domain.yaml"
  # AntiAd:
    # behavior: domain
    # interval: 43200
    # path: ./rule/anti-ad-clash.yaml
    # type: http
    # url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-clash.yaml"
  # AdBlock:
    # behavior: classical
    # interval: 43200
    # path: ./rule/AdBlock.yaml
    # type: http
    # url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/zqzess/rule_for_quantumultX/master/Clash/filter/AdBlock.list"
#
rules:
  #- RULE-SET,myrules,PROXY
  - RULE-SET,mydirect,DIRECT
  - RULE-SET,myproxy,OTHER
  #- RULE-SET,AdBlock,REJECT
  #- RULE-SET,AntiAd,REJECT
  #- RULE-SET,Advertising,REJECT
  #- RULE-SET,Advertising_Domain,REJECT
  #- GEOSITE,category-ads-all,REJECT
# GEOSITE规则
  - GEOSITE,private,DIRECT
  - GEOSITE,youtube,PROXY
  - GEOSITE,google,PROXY
  - GEOSITE,twitter,PROXY
  - GEOSITE,pixiv,PROXY
  - GEOSITE,category-scholar-!cn,PROXY
  #- GEOSITE,biliintl,PROXY
  #- GEOSITE,onedrive,DIRECT
  #- GEOSITE,microsoft@cn,DIRECT
  #- GEOSITE,apple-cn,DIRECT
  - GEOSITE,steam@cn,DIRECT
  - GEOSITE,category-games@cn,DIRECT
  - GEOSITE,geolocation-!cn,PROXY
  #- RULE-SET,proxy,PROXY
  #- RULE-SET,cn,DIRECT
  - GEOSITE,cn,DIRECT
# GEOIP规则
  - GEOIP,private,DIRECT,no-resolve
  - GEOIP,google,PROXY
  - GEOIP,telegram,PROXY
  #- GEOIP,JP,PROXY
  #- GEOIP,US,PROXY
  - GEOIP,CN,DIRECT
  #- DST-PORT,80/8080/443/8443,PROXY
  - MATCH,PROXY
