proxies:
  - name: cloudcone
    server: janeuorg.eu.org
    port: 9154
    type: tuic
    uuid: 8c6c6d9a-054d-4a15-a558-e35311399f8e
    password: 8c6c6d9a-054d-4a15-a558-e35311399f8e
    alpn: [h3]
    disable-sni: true
    reduce-rtt: true
    udp-relay-mode: native
    congestion-controller: bbr
#
  - name: racknerd
    type: vless
    server: www.mareuorg.eu.org
    port: 15204
    uuid: acfbdae5-9e88-4aab-ab29-94f0b644462c
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    servername: 
    reality-opts:
      public-key: 3kktBfu6A4s_I9c4O6ZWGyWKLTyPDzAaCdzNty_mo00
      short-id: 6ba85179e30d4fc2
    client-fingerprint: chrome
#
  - name: virmach
    type: vless
    server: www.febeuorg.eu.org
    port: 443
    uuid: 1704bc5d-2367-4379-821c-aab22d3d6b0a
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    servername: www.febeuorg.eu.org
    reality-opts:
      public-key: pUzSNXGUvmjDxzyddejc3Z4tlo8qWz5tsbv6wwwHWRI
      short-id: 6ba85179e30d4fc2
    client-fingerprint: chrome
