proxies:
  - name: cloudcone
    type: hysteria2
    server: www.janeuorg.eu.org
    port: 14169
    up: "20 Mbps"
    down: "100 Mbps"
    password: b6e5e95e-7cf0-4c9f-9580-9215b8471c80
    sni: www.janeuorg.eu.org
    alpn:
      - h3
#
  - name: racknerd
    server: www.mareuorg.eu.org
    port: 24380
    type: tuic
    uuid: a3af7b69-6f77-4a28-ab52-beac85a3e0cb
    password: a3af7b69-6f77-4a28-ab52-beac85a3e0cb
    alpn: [h3]
    congestion-controller: bbr
#
  - name: virmach
    server: www.febeuorg.eu.org
    port: 16493
    type: tuic
    uuid: 2b2ccaad-e948-49af-9beb-cb70ab95d102
    password: 2b2ccaad-e948-49af-9beb-cb70ab95d102
    alpn: [h3]
    congestion-controller: bbr
