proxies:
  - name: cloudcone
    type: vless
    server: www.janeuorg.eu.org
    port: 17855
    uuid: 45fa3a07-ada8-4c2b-9d12-de24e7fc9f20
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    servername: www.janeuorg.eu.org
    reality-opts:
      public-key: qnyUU4xVJ30JxxSVsDw4SEcGVAT-85hVcEQnNBXBnTw
      short-id: 6ba85179e30d4fc2
    client-fingerprint: chrome
#
  - name: racknerd
    type: vless
    server: www.mareuorg.eu.org
    port: 17458
    uuid: 04c579bb-8cfb-485b-add9-df57849de761
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    servername: www.mareuorg.eu.org
    reality-opts:
      public-key: fBkM2RLIljZwdzFk3e45ym22PPhn4F_pvoYYineuewY
      short-id: 6ba85179e30d4fc2
    client-fingerprint: chrome
#
  - name: virmach
    type: vless
    server: www.febeuorg.eu.org
    port: 23816
    uuid: f7e4f351-1dc4-4f26-b43d-6ca6860613fe
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    servername: www.febeuorg.eu.org
    reality-opts:
      public-key: Hx0Xm8w6k2EvLIAQH6ZwZJWw8rBQVpI5yug78tKxgmo
      short-id: 6ba85179e30d4fc2
    client-fingerprint: chrome
#
  - name: cloudflare
    server: poki.com
    port: 2095
    client-fingerprint: random
    type: vless
    uuid: f72b7917-961c-48dd-9d54-fce30c397586
    tls: false
    tfo: false
    servername: jan.maycloudflare.workers.dev
    skip-cert-verify: true
    network: ws
    ws-opts:
      path: "/?ed=2048"
      headers:
        Host: jan.maycloudflare.workers.dev  
    udp: true
