proxies:
  - name: cloudcone
    type: vless
    server: www.janeuorg.eu.org
    port: 17855
    uuid: 45fa3a07-ada8-4c2b-9d12-de24e7fc9f20
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    servername: www.janeuorg.eu.org
    reality-opts:
      public-key: qnyUU4xVJ30JxxSVsDw4SEcGVAT-85hVcEQnNBXBnTw
      short-id: 6ba85179e30d4fc2
    client-fingerprint: chrome
#
  - name: racknerd
    type: vless
    server: www.mareuorg.eu.org
    port: 17458
    uuid: 04c579bb-8cfb-485b-add9-df57849de761
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    servername: www.mareuorg.eu.org
    reality-opts:
      public-key: fBkM2RLIljZwdzFk3e45ym22PPhn4F_pvoYYineuewY
      short-id: 6ba85179e30d4fc2
    client-fingerprint: chrome
#
  - name: virmach
    type: hysteria2
    server: www.febeuorg.eu.org
    port: 10572
    password: 2fac7fc9-cd2e-4831-95e2-dd716fe0cb27
    sni: www.febeuorg.eu.org
    up: "30 Mbps"
    down: "200 Mbps"
#
  - name: cloudflare
    server: pixabay.com
    port: 2095
    client-fingerprint: random
    type: vless
    uuid: f72b7917-961c-48dd-9d54-fce30c397586
    tls: false
    tfo: false
    servername: jan.maycloudflare.workers.dev
    skip-cert-verify: true
    network: ws
    ws-opts:
      path: "/?ed=2048"
      headers:
        Host: jan.maycloudflare.workers.dev  
    udp: true
