proxies:
  - name: cloudcone
    type: vless
    server: www.janeuorg.eu.org
    port: 19476
    uuid: 998b9b59-ffe2-473b-915c-0d13d372989a
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    servername: www.janeuorg.eu.org
    reality-opts:
      public-key: -qj5OqEgRr8unE7fVDUNQ0LEv_ULe79GHxdWICYLfXI
      short-id: 6ba85179e30d4fc2
    client-fingerprint: chrome
#
  - name: racknerd
    type: vless
    server: www.mareuorg.eu.org
    port: 16973
    uuid: 30b66b57-994e-4c3b-a05a-5628c88d664b
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    servername: www.mareuorg.eu.org
    reality-opts:
      public-key: Ca37Tkx8muSxgtHnN4MSTL3S76ypEvujySGPnzTEkhQ
      short-id: 6ba85179e30d4fc2
    client-fingerprint: chrome
#
  - name: virmach
    type: vless
    server: www.febeuorg.eu.org
    port: 10740
    uuid: 906858b0-bb58-4e33-a411-d1363567729a
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    servername: www.febeuorg.eu.org
    reality-opts:
      public-key: nG0lrn_U-Cn0ihGNa24eU7Wb9f5VhfG6Qhr_7WDM5Qo
      short-id: 6ba85179e30d4fc2
    client-fingerprint: chrome
#
  - name: "cloudflare"
    server: poki.com
    port: 2095
    client-fingerprint: random
    type: vless
    uuid: f72b7917-961c-48dd-9d54-fce30c397586
    tls: false
    tfo: false
    servername: jan.maycloudflare.workers.dev
    skip-cert-verify: true
    network: ws
    ws-opts:
      path: "/?ed=2048"
      headers:
        Host: jan.maycloudflare.workers.dev  
    udp: true
