proxies:
  - name: cloudcone
    type: hysteria2
    server: www.janeuorg.eu.org
    port: 10846
    password: 102c3a5e-abe6-45b6-a041-6f8049c84e31
    sni: www.janeuorg.eu.org
    up: "10 Mbps"
    down: "100 Mbps"
#
  - name: racknerd
    type: hysteria2
    server: www.mareuorg.eu.org
    port: 16941
    password: ec56dc36-2688-4924-9a96-362328352828
    sni: www.mareuorg.eu.org
    up: "10 Mbps"
    down: "100 Mbps"
#
  - name: virmach
    type: hysteria2
    server: www.febeuorg.eu.org
    port: 10572
    password: 2fac7fc9-cd2e-4831-95e2-dd716fe0cb27
    sni: www.febeuorg.eu.org
    up: "10 Mbps"
    down: "100 Mbps"
#
  - name: cloudflare
    server: pixabay.com
    port: 2095
    client-fingerprint: random
    type: vless
    uuid: f72b7917-961c-48dd-9d54-fce30c397586
    tls: false
    tfo: false
    servername: jan.maycloudflare.workers.dev
    skip-cert-verify: true
    network: ws
    ws-opts:
      path: "/?ed=2048"
      headers:
        Host: jan.maycloudflare.workers.dev  
    udp: true
