proxies:
  - name: cloudcone
    type: hysteria2
    server: www.janeuorg.eu.org
    port: 14169
    password: b6e5e95e-7cf0-4c9f-9580-9215b8471c80
    sni: www.janeuorg.eu.org
    alpn:
      - h3
#
  - name: racknerd
    type: hysteria2
    server: www.mareuorg.eu.org
    port: 20229
    password: 5c3aba28-b221-4ab1-b736-7167c69ad34e
    sni: www.mareuorg.eu.org
    alpn:
      - h3
