proxies:
  - name: cloudcone
    type: vless
    server: 142.171.9.118
    port: 443
    uuid: 4cadd3cc-b9ca-4861-a84e-20cc9be695cd
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    servername: www.navitime.co.jp
    reality-opts:
      public-key: LZSlJzAu0bkbGuvhrAE0Gxijps1mMcyCSeP71keVpmc
      short-id: 6ba85179e30d4fc2
    client-fingerprint: chrome
#
  - name: racknerd
    type: vless
    server: www.mareuorg.eu.org
    port: 16973
    uuid: 30b66b57-994e-4c3b-a05a-5628c88d664b
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    servername: www.mareuorg.eu.org
    reality-opts:
      public-key: Ca37Tkx8muSxgtHnN4MSTL3S76ypEvujySGPnzTEkhQ
      short-id: 6ba85179e30d4fc2
    client-fingerprint: chrome
#
  - name: virmach
    type: vless
    server: 141.11.211.57
    port: 443
    uuid: 4046b89d-89a7-4fd1-b91b-4cef836ad249
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    servername: www.navitime.co.jp
    reality-opts:
      public-key: XmODr8YK6KliNX5ZzdsiJDpWndBBNRC1jWBfvk-qzAc
      short-id: 6ba85179e30d4fc2
    client-fingerprint: chrome
