proxies:
  - name: cloudcone
    server: janeuorg.eu.org
    port: 9154
    type: tuic
    uuid: 8c6c6d9a-054d-4a15-a558-e35311399f8e
    password: 8c6c6d9a-054d-4a15-a558-e35311399f8e
    alpn: [h3]
    disable-sni: true
    reduce-rtt: true
    udp-relay-mode: native
    congestion-controller: bbr
#
  - name: racknerd
    type: hysteria
    server: mareuorg.eu.org
    ports: 47000-48000
    auth_str: NxfjIdYUHbSb3ODi6GtZHIpxhQUTBK9W6vgh7gzXyolqdVlLIr
    alpn:
      - h3
    protocol: udp
    up: 22
    down: 110
    sni: mareuorg.eu.org
    skip-cert-verify: false
    recv_window_conn: 11534336
    recv_window: 46137344
    disable_mtu_discovery: true
    fast-open: true
#
  - name: virmach
    server: febeuorg.eu.org
    port: 18442
    type: tuic
    uuid: f3045e18-cb55-461f-b9ef-67432bc0fcf0
    password: f3045e18-cb55-461f-b9ef-67432bc0fcf0
    alpn: [h3]
    disable-sni: true
    reduce-rtt: true
    udp-relay-mode: native
    congestion-controller: bbr
