proxies:
  - name: cloudcone
    type: hysteria
    server: janeuorg.eu.org
    ports: 47000-48000
    auth_str: e6qfWVH0A5dfodGvE5NZNPx898FljWPPPoohjS2SzahUGG9AtW
    alpn:
      - h3
    protocol: udp
    up: 22
    down: 110
    sni: janeuorg.eu.org
    skip-cert-verify: false
    recv_window_conn: 11534336
    recv_window: 46137344
    disable_mtu_discovery: true
    fast-open: true
#
  - name: racknerd
    type: hysteria
    server: mareuorg.eu.org
    ports: 47000-48000
    auth_str: OlESi9qyLrTi0EgCb2JUl3jnKhpy0trgvynPQkib6U0cTnbkCt
    alpn:
      - h3
    protocol: udp
    up: 22
    down: 110
    sni: mareuorg.eu.org
    skip-cert-verify: false
    recv_window_conn: 11534336
    recv_window: 46137344
    disable_mtu_discovery: true
    fast-open: true
#
  - name: virmach
    type: hysteria
    server: febeuorg.eu.org
    ports: 47000-48000
    auth_str: ezRsQ3ro30ynFW2kftIlOAFHUx7YfTBgl1vSrmWQ1xLWHMx4k1
    alpn:
      - h3
    protocol: udp
    up: 22
    down: 110
    sni: febeuorg.eu.org
    skip-cert-verify: false
    recv_window_conn: 11534336
    recv_window: 46137344
    disable_mtu_discovery: true
    fast-open: true
