proxies:
  - name: cloudcone
    server: janeuorg.eu.org
    port: 9154
    type: tuic
    uuid: 8c6c6d9a-054d-4a15-a558-e35311399f8e
    password: 8c6c6d9a-054d-4a15-a558-e35311399f8e
    alpn: [h3]
    disable-sni: true
    reduce-rtt: true
    udp-relay-mode: native
    congestion-controller: bbr
#
  - name: racknerd
    type: vless
    server: 107.173.86.137
    port: 15204
    uuid: acfbdae5-9e88-4aab-ab29-94f0b644462c
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    servername: 
    reality-opts:
      public-key: 3kktBfu6A4s_I9c4O6ZWGyWKLTyPDzAaCdzNty_mo00
      short-id: 6ba85179e30d4fc2
    client-fingerprint: chrome
#
  - name: virmach
    server: febeuorg.eu.org
    port: 18442
    type: tuic
    uuid: f3045e18-cb55-461f-b9ef-67432bc0fcf0
    password: f3045e18-cb55-461f-b9ef-67432bc0fcf0
    alpn: [h3]
    disable-sni: true
    reduce-rtt: true
    udp-relay-mode: native
    congestion-controller: bbr
