proxies:
  - name: cloudcone
    type: vless
    server: www.janeuorg.eu.org
    port: 17855
    uuid: 45fa3a07-ada8-4c2b-9d12-de24e7fc9f20
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    servername: www.janeuorg.eu.org
    reality-opts:
      public-key: qnyUU4xVJ30JxxSVsDw4SEcGVAT-85hVcEQnNBXBnTw
      short-id: 6ba85179e30d4fc2
    client-fingerprint: chrome
#
  - name: racknerd
    type: vless
    server: www.mareuorg.eu.org
    port: 443
    uuid: 36c01922-b5b5-420f-8056-d77545c54458
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    servername: www.formula1.com
    reality-opts:
      public-key: 94UPSXZ9sdWeGTuzsIn9DtJ9TxCvt1O6BuU9saIuklA
      short-id: 6ba85179e30d4fc2
    client-fingerprint: chrome
#
  - name: virmach
    type: vless
    server: www.febeuorg.eu.org
    port: 443
    uuid: 14c349f8-4f3a-4cf0-97f9-8ee7d5c40ace
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    servername: www.thespruce.com
    reality-opts:
      public-key: iHZOZHmtjLBHquBCPQGNPxrj9iwtR79ZpNqnQOX-o0s
      short-id: 6ba85179e30d4fc2
    client-fingerprint: chrome
#
  - name: cloudflare
    server: blaze-1.com
    port: 2095
    client-fingerprint: random
    type: vless
    uuid: f72b7917-961c-48dd-9d54-fce30c397586
    tls: false
    tfo: false
    servername: jan.maycloudflare.workers.dev
    skip-cert-verify: true
    network: ws
    ws-opts:
      path: "/?ed=2048"
      headers:
        Host: jan.maycloudflare.workers.dev  
    udp: true
