proxies:
  - name: cloudcone
    type: hysteria2
    server: www.janeuorg.eu.org
    port: 14169
    up: "20 Mbps"
    down: "100 Mbps"
    password: b6e5e95e-7cf0-4c9f-9580-9215b8471c80
    sni: www.janeuorg.eu.org
    alpn:
      - h3
#
  - name: racknerd
    type: vless
    server: 107.173.86.137
    port: 14811
    uuid: 87f52b70-da6e-4c64-8645-b2439ce8c0c1
    network: tcp
    # tls: true
    # udp: true
    flow: xtls-rprx-vision
    servername: updates.cdn-apple.com
    reality-opts:
      public-key: UwmlQNRWWM0n8S095aKmYnSZ6f0wi5_WsF4VZqaltgY
      short-id: 6ba85179e30d4fc2
    client-fingerprint: chrome
#
  - name: virmach
    type: hysteria
    server: www.febeuorg.eu.org
    ports: 47000-48000
    auth_str: LyZFk2nRPjn0SEtEU7OSvEiyifLH4RFIvxF0RnmHh96sR2AokM
    alpn:
      - h3
    protocol: udp
    up: 22
    down: 110
    sni: www.febeuorg.eu.org
    skip-cert-verify: false
    recv_window_conn: 11534336
    recv_window: 46137344
    disable_mtu_discovery: true
    fast-open: true
