proxies:
  - name: cloudcone
    type: hysteria2
    server: www.janeuorg.eu.org
    port: 14169
    up: "20 Mbps"
    down: "100 Mbps"
    password: b6e5e95e-7cf0-4c9f-9580-9215b8471c80
    sni: www.janeuorg.eu.org
    alpn:
      - h3
#
  - name: racknerd
    type: hysteria
    server: www.mareuorg.eu.org
    ports: 47000-48000
    auth_str: ujtmcXK2WSbwK62v7Wz2pZ1AynXB6gpKMfRlCZokNxlB7mDvQn
    alpn:
      - h3
    protocol: udp
    up: 22
    down: 110
    sni: www.mareuorg.eu.org
    skip-cert-verify: false
    recv_window_conn: 11534336
    recv_window: 46137344
    disable_mtu_discovery: true
    fast-open: true
#
  - name: virmach
    type: hysteria
    server: www.febeuorg.eu.org
    ports: 47000-48000
    auth_str: LyZFk2nRPjn0SEtEU7OSvEiyifLH4RFIvxF0RnmHh96sR2AokM
    alpn:
      - h3
    protocol: udp
    up: 22
    down: 110
    sni: www.febeuorg.eu.org
    skip-cert-verify: false
    recv_window_conn: 11534336
    recv_window: 46137344
    disable_mtu_discovery: true
    fast-open: true
