proxies:
  - name: cloudcone
    type: hysteria2
    server: www.janeuorg.eu.org
    port: 11563
    password: fafb1e52-e75a-4145-8439-286994335882
    sni: www.janeuorg.eu.org
    alpn:
      - h3
#
  - name: racknerd
    type: hysteria2
    server: www.mareuorg.eu.org
    port: 20229
    password: 5c3aba28-b221-4ab1-b736-7167c69ad34e
    sni: www.mareuorg.eu.org
    alpn:
      - h3
#
  - name: virmach
    type: hysteria2
    server: www.febeuorg.eu.org
    port: 18220
    password: d7629dc7-f884-4cbf-a824-edb7934f7934
    sni: www.febeuorg.eu.org
    alpn:
      - h3
