proxies:
  - name: cloudcone
    type: vless
    server: 142.171.9.118
    port: 443
    uuid: 4cadd3cc-b9ca-4861-a84e-20cc9be695cd
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    servername: www.navitime.co.jp
    reality-opts:
      public-key: LZSlJzAu0bkbGuvhrAE0Gxijps1mMcyCSeP71keVpmc
      short-id: 6ba85179e30d4fc2
    client-fingerprint: chrome
#
  - name: racknerd
    type: vless
    server: www.mareuorg.eu.org
    port: 16973
    uuid: 30b66b57-994e-4c3b-a05a-5628c88d664b
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    servername: www.mareuorg.eu.org
    reality-opts:
      public-key: Ca37Tkx8muSxgtHnN4MSTL3S76ypEvujySGPnzTEkhQ
      short-id: 6ba85179e30d4fc2
    client-fingerprint: chrome
#
  - name: virmach
    type: vless
    server: www.febeuorg.eu.org
    port: 10740
    uuid: 906858b0-bb58-4e33-a411-d1363567729a
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    servername: www.febeuorg.eu.org
    reality-opts:
      public-key: nG0lrn_U-Cn0ihGNa24eU7Wb9f5VhfG6Qhr_7WDM5Qo
      short-id: 6ba85179e30d4fc2
    client-fingerprint: chrome
