proxies:
  - name: cloudcone
    type: vless
    server: 142.171.9.118
    port: 443
    uuid: 4cadd3cc-b9ca-4861-a84e-20cc9be695cd
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    servername: www.navitime.co.jp
    reality-opts:
      public-key: LZSlJzAu0bkbGuvhrAE0Gxijps1mMcyCSeP71keVpmc
      short-id: 6ba85179e30d4fc2
    client-fingerprint: chrome
#
  - name: racknerd
    type: vless
    server: 107.173.86.137
    port: 443
    uuid: 87f52b70-da6e-4c64-8645-b2439ce8c0c1
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    servername: www.navitime.co.jp
    reality-opts:
      public-key: sHB4rkdax6zk1OTnHQNQJtc5eymDPMEor-UzQ7zPixY
      short-id: 6ba85179e30d4fc2
    client-fingerprint: chrome
#
  - name: virmach
    type: vless
    server: 141.11.211.57
    port: 443
    uuid: 4046b89d-89a7-4fd1-b91b-4cef836ad249
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    servername: www.navitime.co.jp
    reality-opts:
      public-key: XmODr8YK6KliNX5ZzdsiJDpWndBBNRC1jWBfvk-qzAc
      short-id: 6ba85179e30d4fc2
    client-fingerprint: chrome
