proxies:
  - name: cloudcone
    server: janeuorg.eu.org
    port: 9154
    type: tuic
    uuid: 8c6c6d9a-054d-4a15-a558-e35311399f8e
    password: 8c6c6d9a-054d-4a15-a558-e35311399f8e
    alpn: [h3]
    disable-sni: true
    reduce-rtt: true
    udp-relay-mode: native
    congestion-controller: bbr
#
  - name: racknerd
    server: mareuorg.eu.org
    port: 46867
    type: tuic
    uuid: b52e316d-c3b6-4067-86b4-706007eef6e2
    password: b52e316d-c3b6-4067-86b4-706007eef6e2
    alpn: [h3]
    disable-sni: true
    reduce-rtt: true
    udp-relay-mode: native
    congestion-controller: bbr
#
  - name: virmach
    server: febeuorg.eu.org
    port: 18442
    type: tuic
    uuid: f3045e18-cb55-461f-b9ef-67432bc0fcf0
    password: f3045e18-cb55-461f-b9ef-67432bc0fcf0
    alpn: [h3]
    disable-sni: true
    reduce-rtt: true
    udp-relay-mode: native
    congestion-controller: bbr
