proxies:
  - name: cloudcone
    type: hysteria2
    server: www.janeuorg.eu.org
    port: 28726
    password: 04e55d2b-fd8d-4669-88a5-acc770adfba7
    alpn:
        - h3
    sni: www.janeuorg.eu.org
    up: "50 Mbps"
    down: "100 Mbps"
#
  - name: racknerd
    type: hysteria2
    server: www.mareuorg.eu.org
    port: 19970
    password: 711cec86-6597-48d5-952b-c8c720ea5067
    alpn:
        - h3
    sni: www.mareuorg.eu.org
    up: "50 Mbps"
    down: "100 Mbps"
#
  - name: "vrimach"
    type: hysteria2
    server: www.febeuorg.eu.org
    port: 41040
    password: 7a2b25a4-d6d3-4e53-a9b1-ffab48db370b
    alpn:
        - h3
    sni: www.febeuorg.eu.org
    up: "50 Mbps"
    down: "100 Mbps"
#
  - name: cloudflare
    server: pixabay.com
    port: 2095
    client-fingerprint: random
    type: vless
    uuid: f72b7917-961c-48dd-9d54-fce30c397586
    tls: false
    tfo: false
    servername: jan.maycloudflare.workers.dev
    skip-cert-verify: true
    network: ws
    ws-opts:
      path: "/?ed=2048"
      headers:
        Host: jan.maycloudflare.workers.dev  
    udp: true
